### ISSUE TITLE
Ejercicio 12 esCuadradoPerfecto es muy dificil de repente

### ISSUE THREAD

**Issue by geh** [pdep-utn/mumuki-guia-funcional-practica-valores-y-funciones#4]
Me gusta el ejercicio pero por ahí habría que partirlo en 2. Además se refiere a la recursividad que hasta ahí no se vió en la guía.
(Personalmente lo pude resolver con 2 funciones auxiliares).

**Comment by flbulgarelli** [comment]
Sí, es cierto, habría que moverlo a la guía 17.

**Comment by flbulgarelli** [comment]
@geh vamos a rehacer el ejercicio para que lleve a esta solución: 

``` haskell
esCuadradoPerfecto = (==0).snd.properFraction.sqrt
```

Y agregarlo nuevamente, con la redacción original, en la lección de práctica de recursividad

**Comment by flbulgarelli** [comment]
O incluso mejor:  

``` haskell
esCuadradoPerfecto = esEntero.sqrt
```

**Comment by flbulgarelli** [comment]
Listo. 

http://mumuki.io/exercises/19-programacion-funcional-practica-valores-y-funciones-escuadradoperfecto

http://mumuki.io/exercises/2729-programacion-funcional-practica-recursividad-escuadradoperfecto
